<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title>Celery - 标签 - cywhat&#39;s blog</title>
        <link>https://cywhat.cn/tags/Celery/</link>
        <description>Celery - 标签 - cywhat&#39;s blog</description>
        <generator>Hugo -- gohugo.io</generator><language>zh-CN</language><managingEditor>45204307@qq.com (cywhat)</managingEditor>
            <webMaster>45204307@qq.com (cywhat)</webMaster><copyright>This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.</copyright><lastBuildDate>Fri, 14 Apr 2023 15:51:46 &#43;0800</lastBuildDate><atom:link href="https://cywhat.cn/tags/Celery/" rel="self" type="application/rss+xml" /><item>
    <title>ValueError:invalid</title>
    <link>https://cywhat.cn/ValueErrorinvalid-literal-for-intwithbase10-63790/</link>
    <pubDate>Fri, 14 Apr 2023 15:51:46 &#43;0800</pubDate>
    <author>作者</author>
    <guid>https://cywhat.cn/ValueErrorinvalid-literal-for-intwithbase10-63790/</guid>
    <description><![CDATA[1、前景 使用django的异步调用场景时，并配置了如下配置：出现了错误：ValueError: Database is int between 0 and limit - 1, not :6379/0 1 2 #CELERY_BROKER_URL =&#34;redis://127.0.0.1/:6379/0&#34; #CELERY_BACKEND_URL = &#34;redis://127.0.0.1/:6379/1&#34; 2、原因 1]]></description>
</item></channel>
</rss>
